spring:
  application:
    name: microservicedemo
  config:
    import: configserver:http://localhost:8888

greeting:
  hello: hello world from yaml

my:
  list: one,two,three

app:
  name: myApp
  description: the app, ${app.name}, is used mainly to say hello

db:
  connection: connection-String
  host: 127.0.0.1
  port: 1200

management:
  endpoints:
    web:
      exposure:
        include: "*"